DROP TABLE IF EXISTS TBL_WATCH;

CREATE TABLE TBL_WATCH (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  watchNo VARCHAR(250)  NOT NULL,
  watchName VARCHAR(250) NOT NULL,
  unitPrice INT NOT NULL,
  discountEligibleCount INT DEFAULT NULL,
  discountPrice INT DEFAULT NULL
);